site_name: CopyChat
repo_url: https://github.com/felipeadsm/copychat
repo_name: felipeadsm/copychat
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.png
  
markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css
